baseURL = 'https://wvirany.com/'
languageCode = 'en-us'
title = 'Walter Virany'
theme = 'theme'

# Google analytics code
# googleAnalytics = "G-40CWX6Y06Y"

# Umami Analytics
[params.umami]
enable = true
websiteId = "888cd9bd-9414-47db-bf14-252174c7e592"
src = "https://cloud.umami.is/script.js"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "Blog - Walter Virany"

# Appearance settings
theme = 'light'
colorPalette = 'default' # default, catpuccin, gruvebox, eink
hideHeader = false

# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = false
listDateFormat = 'Jan 2006'

# Breadcrumbs
breadcrumbs = false

# Social icons
[[params.social]]
name = "googlescholar"
url = "https://scholar.google.ca/citations?hl=en&user=S2GA1h8AAAAJ"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/walter-virany/"

[[params.social]]
name = "github"
url = "https://github.com/wvirany"

[[params.social]]
name = "youtube"
url = "https://www.youtube.com/channel/UC3atzAmp5W9vJ2vnOKUYrvA"


# Main menu pages
[[params.menu]]
name = "blog"
url = "/"

# [[params.menu]]
# name = "posts"
# url = "/posts"

[[params.menu]]
name = "me"
url = "/me"

[[params.menu]]
name = "why?"
url = "/why"

# Syntax highlighting on code blocks
[markup]
[markup.highlight]
style = 'vs'

[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true


# Giscus comments
[params.giscus]
enable = true
repo = "wvirany/blog"
repoid = "R_kgDOMs9-zQ"
category = "Blog comments"
categoryid = "DIC_kwDOMs9-zc4CrdIu"
mapping = "pathname"
theme = "noborder_light"